### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by BalmungSan**
Our users deserved it!

----

Ok, I think I covered enough versions, previous releases are just too old for anyone to care IMHO.
Still, this has to be the last PR to merge before the `0.16.0`  release, to ensure all the dates, links and examples are OK.

### CODE REVIEW

**Comment by BalmungSan** [comment]
@dimafeng the changelog / release notes are ready!
Please let me know if you have any comment / recommendation.

When you believe this PR is ready please:
1. Commit directly to this branch to set the appropriate release date [here](https://github.com/BalmungSan/neotypes/blob/add-changelog/site/src/main/mdoc/changelog.md#v0160-2021-02-).
2. Merge this.
3. Release version `0.16.0`

**Comment by dimafeng** [comment]
Hm, tests are failing for some reason. Seems like a testcontainers issue, I'll try to figure out what's going on

**Comment by BalmungSan** [comment]
@dimafeng is related to new version of the graph data since plugin. I was waiting for a while to see if the url will be fixed before reaching to them.

**Comment by BalmungSan** [comment]
@dimafeng it seems the problem with the algorithms jar was fixed, I restarted the pipelines, they should be green in a while.

**Pull request merged**
