### PR TITLE
Zio2 support

### PR DESCRIPTION
**Pull request by masonedmison**
For request #522. This currently uses `2.0.0-RC6` as a placeholder for an official `2.0.0` release. For the most part, this was pretty mechanical, the only bits that might warrant a closer look are 1) `guarantee` and 2) `ZioResource`. Regarding 1, a `ZIO` is constructed with the acquire and release actions that requires a `Scope` in the environment - this scope is eliminated within the scope of this call (using `ZIO.scoped`). Regarding 2, we just return a `ZIO` that has a `Scope` part of the required environment. I _think_ both of these make sense given that I understand the desired semantics.

### CODE REVIEW

**Comment by masonedmison** [comment]
Note that I haven't touched `zio-streams` yet - I assumed that this should be a separate PR but if you think it would make sense, I could take a stab at migrating the streams module as part of this PR, too.

**Comment by BalmungSan** [comment]
> Note that I haven't touched zio-streams yet - I assumed that this should be a separate PR but if you think it would make sense, I could take a stab at migrating the streams module as part of this PR, too.

Ideally it should be a single PR IMHO, I don't like to break main :)

**Comment by masonedmison** [comment]
> Ideally it should be a single PR IMHO, I don't like to break main :)
Fair and makes sense. I'll start working on `zio-streams` then :)

**Comment by masonedmison** [comment]
Ok that was silly, it was pretty trivial to migrate `ZioStream` - for some reason I thought it was going to be more complicated

**Comment by BalmungSan** [comment]
@masonedmison it seems the tests are green! 🎉 
What is failing now are the docs which are still mentioning things like `ZManaged` to generate the docs locally just run `sbt microsite/makeMicrosite`

**Review by BalmungSan — APPROVED** [review]
@masonedmison thanks a lot for looking into this.
I will keep the PR open until the official release; unless you think it would be better to do a release now?

BTW, while I will try to keep a look on when **ZIO** releases, but since you are real users of it I would appreciate if you can remember me once it happens.

**Comment by masonedmison** [comment]
> @masonedmison thanks a lot for looking into this. I will keep the PR open until the official release; unless you think it would be better to do a release now?
@BalmungSan  My pleasure! I will try to contribute something more interesting and technically challenging next time. :) In terms of releasing now or later, I think it would be Ok to release now. I am not really clear on when to expect an official release but I'll circle back here though when the official v2 release is out and make any changes necessary.

**Pull request merged**
