### PR TITLE
Replace tut with mdoc

### LINKED ISSUE #46: Compile documentation examples
Since we are already using [**tut**](https://github.com/tpolecat/tut) due **sbt-microsite**. It would be great if we ensure all our examples are tested to compile with the current version of the application.

Ideally, this should have impact on the CI.
Like, if a PR introduces a change that breaks some example, the PR should not be merged until the documentation is updated accordingly.

### PR DESCRIPTION
**Pull request by BalmungSan**
**tut** is deprecated in favor of **mdoc**, so I decided to make the change.

In the process, I noticed that we weren't compiling our examples, and that most of them were outdated and had typos! _(fixes #46)_

Tasks:

+ [x] Bump **sbt-microsite** to `1.0.0`.
+ [x] Fix all code snippets in the documentation.
+ [x] Fix the layout and links of the documentation.
+ [x] Generate and include the **scaladoc** together with the microsite _(related to #49)_.

### CODE REVIEW

**Comment by dimafeng** [comment]
Wow, great job! For some reason I couldn't run it on my local, after running `./sbt "project microsite" makeMicrosite` and then trying to serve the site from `site/target/site` on my local machine, jekyll is missing some resources. If it works fine for you, feel free to merge the PR.

**Comment by BalmungSan** [comment]
@dimafeng you need to upgrade **Jekyll** to `4.0.0` and install **graphviz**. - It does work for me, but since I changed the layout and the style, I prefer to wait until you can check it, also if you do not like something but you can fix it, I give you access to push to this branch.

**Comment by dimafeng** [comment]
Sure, I'll try to make it work during the weekend

**Comment by BalmungSan** [comment]
@dimafeng Cool :+1:
PS: Please try to make some time to check my gitter message related to travis.

**Comment by dimafeng** [comment]
@BalmungSan it seems that the background on the secondary pages is hardcoded somewhere in MDoc. We can hack it by changing `background: url("../img/bg.jpg") fixed;` to `background: url(../img/bg.jpg) fixed !important;` in style.css

**Pull request merged**
