### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by BalmungSan**
- [x] `core`: Drop support for Scala **2.11**.
- [x] `core`: Adding support for Scala **2.13**.
- [x] `core`: Adding support for Scala **2.13** _(tests)_.
- [x] `core`: Cross build for Scala **2.13** & **2.12**.
- [x] `modules`: Upgrade to Scala **2.13**.
- [x] `modules`: Wait for official releases of dependencies _(i.e. no milestone or release candidate versions)_.

### CODE REVIEW

**Comment by BalmungSan** [comment]
Since the new collections framework makes it more _"easy"_ _(as easy as simple in SBT 🤣)_ to support any kind of collection. I decided to do that for **neotypes**.

So far, everything seems to work. There was only one minor regression _(explained in the review comments)_.

**Comment by BalmungSan** [comment]
Ok, cross building between Scala `2.12` & `2.13` is done 😃

**Comment by BalmungSan** [comment]
Ok, while this is not ready to be merged, all the heavy work should be done. Thus, this is ready for review.

For now, we should just wait until Monix provides support for Scala **2.13** and that all that cats and fs2 made an official _(non milestone or release candidate)_ release.

**Comment by dimafeng** [comment]
@BalmungSan sorry, I haven't had access to the computer to review. But seems I'll have some time tomorrow or on Wednesday. Hope it doesn't block any of your development efforts.

**Comment by dimafeng** [comment]
@BalmungSan finally finished! Looks good to me. Great job 🚀

**Comment by BalmungSan** [comment]
@dimafeng *We are ready!!* 🎉 
I am going to merge this as soon as the tests finish.

Hope you can do a new release _as soon as possible_. Looking forward for it.

**Comment by dimafeng** [comment]
@BalmungSan done! 💯

**Pull request merged**
