### PR TITLE
WIP Unify Tests To WordSpec

### PR DESCRIPTION
**Pull request by geoffjohn11**

### CODE REVIEW

**Comment by geoffjohn11** [comment]
@BalmungSan What do you think of this style/layout?  I haven't changed the assertions to matchers yet.

**Comment by BalmungSan** [comment]
@geoffjohn11 I gave it a quick look and it looks nice.
I will obviously review it carefully when the PR is ready.

Just one little thing: Be very careful about style, on my quick review I noticed:
+ Some missing spaces before / after braces _(`{`)_
+ Some extra _(and unnecessary)_ new lines.
+ Some missing empty lines between each test.
+ etc.

---

>  I haven't changed the assertions to matchers yet.

Yeah, no worries. That probably will be the biggest change.

**Comment by geoffjohn11** [comment]
@BalmungSan I'm a little confused about what formatting we are aiming for with this refactor.  In MapperSpec there are both empty lines between tests, and no empty lines between tests.  In this refactor do you want empty lines between tests?  Can you give me an example of a issue with spacing and curly braces?  In the code below I don't put a space before or after the curly braces.  Is that not desired?
```java
 "summon implicit ResultMapper instances" in {
      val strMapper = ResultMapper[String]
      assert(strMapper == StringResultMapper)
    }
```

**Comment by BalmungSan** [comment]
@geoffjohn11 you can take a look at the [**StageSyntaxSpec**](https://github.com/neotypes/neotypes/blob/master/core/src/test/scala/neotypes/internal/syntax/StageSyntaxSpec.scala) and the [**AsyncGuaranteeSpec**](https://github.com/neotypes/neotypes/blob/master/core/src/test/scala/neotypes/AsyncGuaranteeSpec.scala) for general guidelines.

The TL;DR; is simple.
1. Always add a space before and after an opening curly brace. E.g. **Good**: `foo { bar =>` - **Bad**: `foo{ bar=>` | `foo {bar =>`
2. Always add one _(and only one)_ empty line between tests, this helps in quickly identifying where one test ends and where another one begins.

If you have specific questions feel free to tag me in the **gitter** channel, I will answer ASAP.

**Comment by BalmungSan** [comment]
Once `0.16.0` is released we should give fresh air to this!

**Comment by geoffjohn11** [comment]
too many merge conflicts

**Pull request closed without merging**
